#!/bin/bash
cd  /home/"$USER"/sistemas/linux/ejercicios/ut3_2/

mkdir VEHICULOS BARCOS 

mkdir /VEHICULOS /2RUEDAS 4RUEDAS
mkdir /VEHICULOS/2RUEDAS/BICI MOTO
mkdir /VEHICULOS/4RUEDAS/COCHE FURGONETA

mkdir /BARCOS/LANCHA VELEROS YATES
 